version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: market-data-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:15
    container_name: market-data-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketdata"]
      interval: 10s
      timeout: 5s
      retries: 5

  market_data:
    build: .
    container_name: market-data-service
    command: ["python", "-m", "market_data.app"]
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379/0
      REDIS_TICK_STREAM: marketdata_ticks
      REDIS_ORDER_BOOK_STREAM: marketdata_order_books
      REDIS_DEALER_QUOTE_STREAM: marketdata_dealer_quotes
      POSTGRES_DSN: postgresql://postgres:postgres@postgres:5432/marketdata
      POSTGRES_SCHEMA: public
      MARKET_DATA_INTERVAL_SECONDS: "0.2"
      MARKET_DATA_HTTP_HOST: 0.0.0.0
      MARKET_DATA_HTTP_PORT: "8080"
      MARKET_DATA_CORS_ORIGINS: http://localhost:5173
    volumes:
      - .:/app:ro
    ports:
      - "8080:8080"

  trading_agent:
    build: .
    container_name: trading-agent-service
    command:
      [
        "uvicorn",
        "trading.app:create_default_app",
        "--factory",
        "--host",
        "0.0.0.0",
        "--port",
        "8081",
      ]
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      market_data:
        condition: service_started
    environment:
      TRADING_REDIS_URL: redis://redis:6379/0
      TRADING_POSTGRES_DSN: postgresql://postgres:postgres@postgres:5432/marketdata
      TRADING_MARKETDATA_STREAM: marketdata_stream
      TRADING_EXECUTION_STREAM: execution_stream
      TRADING_ORDER_STREAM: order_commands
      TRADING_CORS_ORIGINS: http://localhost:5173
      TRADING_SESSION_COOKIE_NAME: session_id
      TRADING_SESSION_TTL_MINUTES: "60"
    volumes:
      - .:/app:ro

  auth_service:
    build: .
    container_name: auth-service
    command:
      [
        "uvicorn",
        "auth.server:create_default_app",
        "--factory",
        "--host",
        "0.0.0.0",
        "--port",
        "8082",
      ]
    ports:
      - "8082:8082"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      AUTH_POSTGRES_DSN: postgresql://postgres:postgres@postgres:5432/marketdata
      AUTH_POSTGRES_SCHEMA: public
      AUTH_REDIS_URL: redis://redis:6379/0
      AUTH_SESSION_TTL_MINUTES: "60"
      AUTH_SECURE_COOKIES: "false"
      AUTH_CORS_ORIGINS: http://localhost:5173
    volumes:
      - .:/app:ro

volumes:
  postgres-data:
